// <auto-generated />
using LogMount.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LogMount.Migrations
{
    [DbContext(typeof(LogMountDbContext))]
    [Migration("20260811073000_AddAutoImportStates")]
    partial class AddAutoImportStates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
